# DECIPY

https://github.com/realnoobs/decipy

In [122]:
import numpy as np
import pandas as pd
from decipy import executors as exe

In [123]:
data = pd.read_excel("VIKOR.xlsx", index_col=0)

In [124]:
data

Yakit  Max_Hiz  Agirlik  Silindir_Hacmi   HP  CO2  Bagaj    Fiyat
Giulietta    5.2      218     1310            1368  170  121    350   74.385
A3           4.7      213     1310            1395  140  110    380   86.523
M3          11.5      250     1480            1586  420  269    350  102.705
A250         6.4      240     1445            1991  211  148    341  145.200
Mini         6.4      225     1305            1598  260  149    170   84.399
BRS          7.8      226     1256            1998  200  181    243  121.803
Golf         5.2      203     1249            1395  122  116    380   61.000
V 40         5.3      210     1474            1596  150   99    324   81.710

In [125]:
# alternatifler
alts = data.index

# kriterler
crits = data.columns

# kriterin fayda değerleri. Fayda için True veya maliyet için False
beneficial = [False, True, True, True, True, False, True, False]

# kriter ağırlıkları
weights = [0.15, 0.18, 0.11, 0.9, 0.12, 0.13, 0.08, 0.14]

In [126]:
kwargs = {
    'data': data,
    'beneficial': beneficial,
    'weights': weights,
    'rank_reverse': True,
    'rank_method': "ordinal"
}

In [127]:
# Build MCDM Executor
wsm = exe.WSM(**kwargs) # Agirlikli Ortalama
topsis = exe.Topsis(**kwargs) # Topsis 
vikor = exe.Vikor(**kwargs) # Vikor 

# show results
print("WSM Ranks")
print(wsm.dataframe)

print("TOPSIS Ranks")
print(topsis.dataframe)

print("Vikor Ranks")
print(vikor.dataframe)

WSM Ranks
             RATE  RANK
Giulietta  0.5443   7.0
A3         0.5624   6.0
M3         0.8607   4.0
A250       1.4309   1.0
Mini       0.8006   5.0
BRS        1.2384   2.0
Golf       0.5146   8.0
V 40       0.9020   3.0
TOPSIS Ranks
               D+      D-    RATE  RANK
Giulietta  0.1329  0.0546  0.2911   8.0
A3         0.1309  0.0584  0.3084   7.0
M3         0.1015  0.0743  0.4225   4.0
A250       0.0625  0.1271  0.6705   1.0
Mini       0.0921  0.0629  0.4060   5.0
BRS        0.0678  0.1252  0.6487   2.0
Golf       0.1313  0.0630  0.3241   6.0
V 40       0.0958  0.0725  0.4308   3.0
Vikor Ranks
                S       P    RATE  RANK
Giulietta  1.3209  0.9000  0.9970   8.0
A3         1.2888  0.8617  0.9543   6.0
M3         0.9780  0.5886  0.6038   4.0
A250       0.4399  0.1400  0.0125   1.0
Mini       1.0981  0.5714  0.6605   5.0
BRS        0.6541  0.1205  0.1208   2.0
Golf       1.3263  0.8617  0.9754   7.0
V 40       0.9509  0.5747  0.5796   3.0


In [128]:
# En iyi yöntemi seçme & Sıralama Analizi
analizer = exe.RankSimilarityAnalyzer()

analizer.add_executor(wsm)
analizer.add_executor(topsis)
analizer.add_executor(vikor)

results = analizer.analyze()
print(results)

[0.9683 0.9683 0.9841]


# PYMCDM

https://gitlab.com/shekhand/mcda/-/blob/master/examples/examples.ipynb

In [129]:
import numpy as np
import pandas as pd

#Tablolaştırmak için
from tabulate import tabulate

#Karar Kütüphanesi
from pymcdm import methods as mcdm_methods
from pymcdm import weights as mcdm_weights
from pymcdm import normalizations as norm
from pymcdm import correlations as corr
from pymcdm.helpers import rankdata, rrankdata

In [130]:
matrix = data[data.columns[0:]].to_numpy()
print(matrix)

[[   5.2    218.    1310.    1368.     170.     121.     350.      74.385]
 [   4.7    213.    1310.    1395.     140.     110.     380.      86.523]
 [  11.5    250.    1480.    1586.     420.     269.     350.     102.705]
 [   6.4    240.    1445.    1991.     211.     148.     341.     145.2  ]
 [   6.4    225.    1305.    1598.     260.     149.     170.      84.399]
 [   7.8    226.    1256.    1998.     200.     181.     243.     121.803]
 [   5.2    203.    1249.    1395.     122.     116.     380.      61.   ]
 [   5.3    210.    1474.    1596.     150.      99.     324.      81.71 ]]


In [131]:
agirlik = np.array([0.15, 0.18, 0.11, 0.9, 0.12, 0.13, 0.08, 0.14])
kriter = np.array([-1, 1, 1, 1, 1, -1, 1, -1])

In [132]:
vikor = mcdm_methods.VIKOR()
sonuc=vikor(matrix, agirlik, kriter,)
print(sonuc)

[0.9838 0.9496 0.6149 0.021  0.637  0.1051 0.9757 0.5834]


In [133]:
sıra=rankdata(sonuc, reverse=False)
print(sıra)

[8. 6. 4. 1. 5. 2. 7. 3.]


In [136]:
data['VIKOR'] = sonuc.tolist()
data['Sıralama'] = sıra.tolist()

In [137]:
data

Yakit  Max_Hiz  Agirlik  Silindir_Hacmi   HP  CO2  Bagaj    Fiyat  \
Giulietta    5.2      218     1310            1368  170  121    350   74.385   
A3           4.7      213     1310            1395  140  110    380   86.523   
M3          11.5      250     1480            1586  420  269    350  102.705   
A250         6.4      240     1445            1991  211  148    341  145.200   
Mini         6.4      225     1305            1598  260  149    170   84.399   
BRS          7.8      226     1256            1998  200  181    243  121.803   
Golf         5.2      203     1249            1395  122  116    380   61.000   
V 40         5.3      210     1474            1596  150   99    324   81.710   

              VIKOR  Sıralama  
Giulietta  0.983773       8.0  
A3         0.949627       6.0  
M3         0.614898       4.0  
A250       0.021008       1.0  
Mini       0.636955       5.0  
BRS        0.105070       2.0  
Golf       0.975690       7.0  
V 40       0.583374       3.0